/** Roster for Knesset Kombat 26. Attack lines: /voices/<id>/words/*.mp3 (real politician speech). */

export const CHARACTERS = [
  {
    id: 'bibi',
    name: 'Bibi',
    fullName: 'Benjamin Netanyahu',
    title: 'The Survivor',
    color: '#0b1f4a',
    accent: '#3b82f6',
    shirt: '#f8fafc',
    tie: '#2563eb',
    moves: { punch: 9, kick: 13, special: 20 },
    specialName: 'Coalition Crush',
    finalSmash: {
      name: 'Lobby Leak',
      caption: 'Senate, Congress… and a record-strong lobby',
      clip: './finalsmashes/bibi.mp4',
      voice: './voices/announcer/bibi-fs.mp3',
    },
    avatar: './avatars/bibi.png',
    // Compact older statesman — medium height, solid midsection
    body: {
      height: 0.96,
      torsoW: 1.12,
      torsoH: 0.95,
      shoulder: 1.08,
      arm: 1.0,
      leg: 0.98,
      head: 1.02,
      skin: '#d7b08c',
      hair: '#c5c9ce',
      style: 'statesman',
      props: ['silverHair', 'blueTie', 'flagPin'],
    },
    attackWords: [
      './voices/bibi/words/w00.mp3',
      './voices/bibi/words/w01.mp3',
      './voices/bibi/words/w02.mp3',
      './voices/bibi/words/w03.mp3',
      './voices/bibi/words/w04.mp3',
      './voices/bibi/words/w05.mp3',
      './voices/bibi/words/w06.mp3',
      './voices/bibi/words/w07.mp3',
    ],
    voices: {
      attack: './voices/bibi/attack.wav',
      hurt: './voices/bibi/hurt.wav',
      victory: './voices/bibi/victory.wav',
    },
  },
  {
    id: 'lapid',
    name: 'Lapid',
    fullName: 'Yair Lapid',
    title: 'Smooth Operator',
    color: '#1e293b',
    accent: '#94a3b8',
    shirt: '#ffffff',
    tie: '#0f172a',
    moves: { punch: 8, kick: 12, special: 18 },
    specialName: 'Prime Time Punch',
    finalSmash: {
      name: 'Rules Refused',
      caption: 'Washington asks. Lapid rebuffs.',
      clip: './finalsmashes/lapid.mp4',
      voice: './voices/announcer/lapid-fs.mp3',
    },
    avatar: './avatars/lapid.png',
    // Taller, leaner former-boxer frame
    body: {
      height: 1.05,
      torsoW: 0.92,
      torsoH: 1.05,
      shoulder: 1.0,
      arm: 1.05,
      leg: 1.08,
      head: 0.98,
      skin: '#d9b491',
      hair: '#9aa0a8',
      style: 'lean',
      props: ['silverWavyHair', 'darkTie'],
    },
    attackWords: [
      './voices/lapid/words/w00.mp3',
      './voices/lapid/words/w01.mp3',
      './voices/lapid/words/w02.mp3',
      './voices/lapid/words/w03.mp3',
      './voices/lapid/words/w04.mp3',
      './voices/lapid/words/w05.mp3',
      './voices/lapid/words/w06.mp3',
      './voices/lapid/words/w07.mp3',
      './voices/lapid/words/w08.mp3',
      './voices/lapid/words/w09.mp3',
    ],
    voices: {
      attack: './voices/lapid/attack.wav',
      hurt: './voices/lapid/hurt.wav',
      victory: './voices/lapid/victory.wav',
    },
  },
  {
    id: 'gantz',
    name: 'Gantz',
    fullName: 'Benny Gantz',
    title: 'The General',
    color: '#3f4f2f',
    accent: '#a3b18a',
    shirt: '#e8eee4',
    tie: null,
    moves: { punch: 10, kick: 14, special: 19 },
    specialName: 'Iron Dome Drop',
    finalSmash: {
      name: 'Coalition Crumble',
      caption: 'Ready for Netanyahu to go — on camera',
      clip: './finalsmashes/gantz.mp4',
      voice: './voices/announcer/gantz-fs.mp3',
    },
    avatar: './avatars/gantz.png',
    // Very tall, broad-shouldered military build
    body: {
      height: 1.14,
      torsoW: 1.2,
      torsoH: 1.1,
      shoulder: 1.28,
      arm: 1.12,
      leg: 1.15,
      head: 1.0,
      skin: '#d4ae86',
      hair: '#d7dbe0',
      style: 'military',
      props: ['recedingHair', 'openCollar'],
    },
    attackWords: [
      './voices/gantz/words/w00.mp3',
      './voices/gantz/words/w01.mp3',
      './voices/gantz/words/w02.mp3',
      './voices/gantz/words/w03.mp3',
      './voices/gantz/words/w04.mp3',
      './voices/gantz/words/w05.mp3',
      './voices/gantz/words/w06.mp3',
      './voices/gantz/words/w07.mp3',
      './voices/gantz/words/w08.mp3',
      './voices/gantz/words/w09.mp3',
    ],
    voices: {
      attack: './voices/gantz/attack.wav',
      hurt: './voices/gantz/hurt.wav',
      victory: './voices/gantz/victory.wav',
    },
  },
  {
    id: 'bengvir',
    name: 'Ben-Gvir',
    fullName: 'Itamar Ben-Gvir',
    title: 'Firebrand',
    color: '#111111',
    accent: '#e5e7eb',
    shirt: '#ffffff',
    tie: '#111111',
    moves: { punch: 11, kick: 12, special: 21 },
    specialName: 'Otterman Blitz',
    finalSmash: {
      name: 'Temple Mount Raid',
      caption: 'Al-Aqsa morning walk. International headlines.',
      clip: './finalsmashes/bengvir.mp4',
      voice: './voices/announcer/bengvir-fs.mp3',
    },
    avatar: './avatars/bengvir.png',
    // Shorter, stockier; white kippah + glasses
    body: {
      height: 0.92,
      torsoW: 1.22,
      torsoH: 0.9,
      shoulder: 1.15,
      arm: 0.95,
      leg: 0.9,
      head: 1.08,
      skin: '#e0c2a0',
      hair: '#5b5f66',
      style: 'stocky',
      props: ['whiteKippah', 'glasses', 'blackTie', 'stubble'],
    },
    attackWords: [
      './voices/bengvir/words/w00.mp3',
      './voices/bengvir/words/w01.mp3',
      './voices/bengvir/words/w02.mp3',
      './voices/bengvir/words/w03.mp3',
      './voices/bengvir/words/w04.mp3',
      './voices/bengvir/words/w05.mp3',
      './voices/bengvir/words/w06.mp3',
      './voices/bengvir/words/w07.mp3',
      './voices/bengvir/words/w08.mp3',
      './voices/bengvir/words/w09.mp3',
    ],
    voices: {
      attack: './voices/bengvir/attack.wav',
      hurt: './voices/bengvir/hurt.wav',
      victory: './voices/bengvir/victory.wav',
    },
  },
  {
    id: 'smotrich',
    name: 'Smotrich',
    fullName: 'Bezalel Smotrich',
    title: 'Budget Blade',
    color: '#1e3a5f',
    accent: '#7dd3fc',
    shirt: '#ffffff',
    tie: '#1d4ed8',
    moves: { punch: 8, kick: 13, special: 22 },
    specialName: 'Austerity Slash',
    finalSmash: {
      name: 'Paris Map Meltdown',
      caption: 'Paris, 2023 — “The Palestinian people don’t exist.”',
      clip: './finalsmashes/smotrich.mp4',
      voice: './voices/announcer/smotrich-fs.mp3',
    },
    avatar: './avatars/smotrich.png',
    // Medium frame, knitted kippah, full beard
    body: {
      height: 0.98,
      torsoW: 1.05,
      torsoH: 1.0,
      shoulder: 1.05,
      arm: 1.0,
      leg: 1.0,
      head: 1.0,
      skin: '#e6c7a6',
      hair: '#4a3728',
      style: 'religious',
      props: ['knitKippah', 'fullBeard', 'blueTie'],
    },
    attackWords: [
      './voices/smotrich/words/w00.mp3',
      './voices/smotrich/words/w01.mp3',
      './voices/smotrich/words/w02.mp3',
      './voices/smotrich/words/w03.mp3',
      './voices/smotrich/words/w04.mp3',
      './voices/smotrich/words/w05.mp3',
      './voices/smotrich/words/w06.mp3',
      './voices/smotrich/words/w07.mp3',
      './voices/smotrich/words/w08.mp3',
      './voices/smotrich/words/w09.mp3',
    ],
    voices: {
      attack: './voices/smotrich/attack.wav',
      hurt: './voices/smotrich/hurt.wav',
      victory: './voices/smotrich/victory.wav',
    },
  },
  {
    id: 'lieberman',
    name: 'Lieberman',
    fullName: 'Avigdor Lieberman',
    title: 'Iron Fist',
    color: '#1f2937',
    accent: '#d1d5db',
    shirt: '#ffffff',
    tie: '#374151',
    moves: { punch: 10, kick: 15, special: 18 },
    specialName: 'Veto Smash',
    finalSmash: {
      name: 'No Concessions',
      caption: 'Land for peace? Lieberman says no.',
      clip: './finalsmashes/lieberman.mp4',
      voice: './voices/announcer/lieberman-fs.mp3',
    },
    avatar: './avatars/lieberman.png',
    // Heavy-set solid build, gray goatee
    body: {
      height: 0.94,
      torsoW: 1.3,
      torsoH: 0.92,
      shoulder: 1.22,
      arm: 1.05,
      leg: 0.92,
      head: 1.1,
      skin: '#d9b89a',
      hair: '#d8d8d8',
      style: 'heavy',
      props: ['grayGoatee', 'recedingGray', 'darkTie'],
    },
    attackWords: [
      './voices/lieberman/words/w00.mp3',
      './voices/lieberman/words/w01.mp3',
      './voices/lieberman/words/w02.mp3',
      './voices/lieberman/words/w03.mp3',
      './voices/lieberman/words/w04.mp3',
      './voices/lieberman/words/w05.mp3',
      './voices/lieberman/words/w06.mp3',
      './voices/lieberman/words/w07.mp3',
    ],
    voices: {
      attack: './voices/lieberman/attack.wav',
      hurt: './voices/lieberman/hurt.wav',
      victory: './voices/lieberman/victory.wav',
    },
  },
]

export const BLOCK_DAMAGE_FACTOR = 0.15 // blocking reduces damage by 85%
export const MAX_HEALTH = 100
export const ROUND_SECONDS = 60
